// connection
export const CONNECT = "CONNECT";
export const FINILIZE_CONNECTION = "FINILIZE_CONNECTION";
export const DISCONNECT = "DISCONNECT";
export const REQUEST_DEVICE = "REQUEST_DEVICE";
export const CHANGE_SERVICE_UUID ="CHANGE_SERVICE_UUID"
export const CHANGE_CHARACTERISTIC_UUID ="CHANGE_CHARACTERISTIC_UUID"
export const CHANGE_LOG_OUTPUT_TEXT ="CHANGE_LOG_OUTPUT_TEXT"
export const FLUSH_LOG_OUTPUT_TEXT = "FLUSH_LOG_OUTPUT_TEXT"

// settings
export const BRIGHTNESS = "BRIGHTNESS"

// animations
export const PLAY_ANIMATION = "PLAY_ANIMATION"
export const STOP_ANIMATION = "STOP_ANIMATION"
export const SET_DELAY = "SET_DELAY"
export const SET_COLOR = "SET_COLOR"
export const SET_ANIMATION = "SET_ANIMATION"

// games
export const PLAY_GAME = "PLAY_GAME"
export const STOP_GAME = "STOP_GAME"
export const SET_GAME_SPEED = "SET_GAME_SPEED"
export const SET_GAME = "SET_GAME"